version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: edusmart_db_prod
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: edusmart_prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data # Les données réelles sont stockées ici de manière permanente

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edusmart_app_prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/edusmart_prod?schema=public"
      JWT_SECRET: ${JWT_SECRET}
      PAYTECH_SECRET_KEY: ${PAYTECH_SECRET_KEY}
      PAYTECH_API_KEY: ${PAYTECH_API_KEY}
    depends_on:
      - postgres

volumes:
  postgres_prod_data: # Volume persistant
